beelab_paypal:
    return_route: keep_transaction
    cancel_route: cancel_transaction
    test_mode: "%kernel.debug%"
    username: "armando25723"
    password: "123qweasdzxc"
    signature: "cubaGPS"