payum:
    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payment: { doctrine: orm }

    gateways:
        stripe:
             factory:   stripe_checkout
             publishable_key:  'pk_test_8486tSb8zy9b8KvQoGZau3zj'
             secret_key:  'sk_test_4y0or8pcissfTdR32kd6wRXR'
