payum:
    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payment: { doctrine: orm }

    gateways:
        paypal:
             factory: paypal_express_checkout
             username:  'cubagps_api2.yahoo.com'
             password:  'VDWZD4G83K7JVDM4'
             signature: 'A5YPN42nAqrFrjs0hlHJtuQfp0SuAIVTU-4u3.iJTwfhY7T9B3U5Dg8A'
             sandbox: false