payum:
    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payment: { doctrine: orm }

    gateways:
        paypal:
             factory: paypal_express_checkout
             username:  'cubagps_api2.yahoo.com'
             password:  'VDWZD4G83K7JVDM4'
             signature: 'AmH177qxMLAtqir0oGPBXnwl6iL3AzUCG10Rzf8531T9PeA.vz6VMH9V'
             sandbox: false