swiftmailer:
        transport:        gmail
        username:         cubagps@gmail.com
        password:         cubaGPS*-
        host:             localhost
        port:             25
        encryption:       ssl
        auth-mode:        login
        spool: { type: 'memory' }
        stream_options:
            ssl:
                allow_self_signed: true
                verify_peer: false
                verify_peer_name: false