<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\AddUserCommand' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\src\\Command\\AddUserCommand.php';
include_once $this->targetDirs[3].'\\src\\Utils\\Validator.php';

$this->privates['App\Command\AddUserCommand'] = $instance = new \App\Command\AddUserCommand(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php')), ($this->privates['App\Utils\Validator'] ?? $this->privates['App\Utils\Validator'] = new \App\Utils\Validator()), ($this->privates['App\Repository\UserRepository'] ?? $this->load(__DIR__.'/getUserRepositoryService.php')));

$instance->setName('app:add-user');

return $instance;
