<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Admin\\BlogController:index' => function () {
    return ($this->privates['service_locator.6bwwuNV'] ?? $this->load(__DIR__.'/getServiceLocator_6bwwuNVService.php'));
}, 'App\\Controller\\AreaController:areas' => function () {
    return ($this->privates['service_locator.DD4RxCj'] ?? $this->load(__DIR__.'/getServiceLocator_DD4RxCjService.php'));
}, 'App\\Controller\\AreaController:checkAreaName' => function () {
    return ($this->privates['service_locator.h46VmrW'] ?? $this->load(__DIR__.'/getServiceLocator_H46VmrWService.php'));
}, 'App\\Controller\\BlogController:commentNew' => function () {
    return ($this->privates['service_locator.e0kEKNf'] ?? $this->load(__DIR__.'/getServiceLocator_E0kEKNfService.php'));
}, 'App\\Controller\\BlogController:index' => function () {
    return ($this->privates['service_locator.1Iq9ywg'] ?? $this->load(__DIR__.'/getServiceLocator_1Iq9ywgService.php'));
}, 'App\\Controller\\BlogController:search' => function () {
    return ($this->privates['service_locator.rIerrUe'] ?? $this->load(__DIR__.'/getServiceLocator_RIerrUeService.php'));
}, 'App\\Controller\\SecurityController:checkRegistered' => function () {
    return ($this->privates['service_locator.ELQewQI'] ?? $this->load(__DIR__.'/getServiceLocator_ELQewQIService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.Syn2D.o'] ?? $this->load(__DIR__.'/getServiceLocator_Syn2D_OService.php'));
}, 'App\\Controller\\SecurityController:registerSistem' => function () {
    return ($this->privates['service_locator.CHkNi47'] ?? $this->load(__DIR__.'/getServiceLocator_CHkNi47Service.php'));
}, 'App\\Controller\\UserController:checkUserName' => function () {
    return ($this->privates['service_locator.Fg.7mrD'] ?? $this->load(__DIR__.'/getServiceLocator_Fg_7mrDService.php'));
}, 'App\\Controller\\UserController:createUser' => function () {
    return ($this->privates['service_locator.kYG.7AJ'] ?? $this->load(__DIR__.'/getServiceLocator_KYG_7AJService.php'));
}, 'App\\Controller\\UserController:delete_user' => function () {
    return ($this->privates['service_locator.txhAz4U'] ?? $this->load(__DIR__.'/getServiceLocator_TxhAz4UService.php'));
}, 'App\\Controller\\UserController:process_user' => function () {
    return ($this->privates['service_locator._IK4IyU'] ?? $this->load(__DIR__.'/getServiceLocator_IK4IyUService.php'));
}, 'App\\Controller\\UserController:users' => function () {
    return ($this->privates['service_locator.txhAz4U'] ?? $this->load(__DIR__.'/getServiceLocator_TxhAz4UService.php'));
}, 'App\\Controller\\Admin\\BlogController::index' => function () {
    return ($this->privates['service_locator.6bwwuNV'] ?? $this->load(__DIR__.'/getServiceLocator_6bwwuNVService.php'));
}, 'App\\Controller\\AreaController::areas' => function () {
    return ($this->privates['service_locator.DD4RxCj'] ?? $this->load(__DIR__.'/getServiceLocator_DD4RxCjService.php'));
}, 'App\\Controller\\AreaController::checkAreaName' => function () {
    return ($this->privates['service_locator.h46VmrW'] ?? $this->load(__DIR__.'/getServiceLocator_H46VmrWService.php'));
}, 'App\\Controller\\BlogController::commentNew' => function () {
    return ($this->privates['service_locator.e0kEKNf'] ?? $this->load(__DIR__.'/getServiceLocator_E0kEKNfService.php'));
}, 'App\\Controller\\BlogController::index' => function () {
    return ($this->privates['service_locator.1Iq9ywg'] ?? $this->load(__DIR__.'/getServiceLocator_1Iq9ywgService.php'));
}, 'App\\Controller\\BlogController::search' => function () {
    return ($this->privates['service_locator.rIerrUe'] ?? $this->load(__DIR__.'/getServiceLocator_RIerrUeService.php'));
}, 'App\\Controller\\SecurityController::checkRegistered' => function () {
    return ($this->privates['service_locator.ELQewQI'] ?? $this->load(__DIR__.'/getServiceLocator_ELQewQIService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.Syn2D.o'] ?? $this->load(__DIR__.'/getServiceLocator_Syn2D_OService.php'));
}, 'App\\Controller\\SecurityController::registerSistem' => function () {
    return ($this->privates['service_locator.CHkNi47'] ?? $this->load(__DIR__.'/getServiceLocator_CHkNi47Service.php'));
}, 'App\\Controller\\UserController::checkUserName' => function () {
    return ($this->privates['service_locator.Fg.7mrD'] ?? $this->load(__DIR__.'/getServiceLocator_Fg_7mrDService.php'));
}, 'App\\Controller\\UserController::createUser' => function () {
    return ($this->privates['service_locator.kYG.7AJ'] ?? $this->load(__DIR__.'/getServiceLocator_KYG_7AJService.php'));
}, 'App\\Controller\\UserController::delete_user' => function () {
    return ($this->privates['service_locator.txhAz4U'] ?? $this->load(__DIR__.'/getServiceLocator_TxhAz4UService.php'));
}, 'App\\Controller\\UserController::process_user' => function () {
    return ($this->privates['service_locator._IK4IyU'] ?? $this->load(__DIR__.'/getServiceLocator_IK4IyUService.php'));
}, 'App\\Controller\\UserController::users' => function () {
    return ($this->privates['service_locator.txhAz4U'] ?? $this->load(__DIR__.'/getServiceLocator_TxhAz4UService.php'));
})));
