<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.1Iq9ywg' shared service.

return $this->privates['service_locator.1Iq9ywg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('sistemRepository' => function (): ?\App\Repository\SistemRepository {
    return ($this->privates['App\Repository\SistemRepository'] ?? $this->load(__DIR__.'/getSistemRepositoryService.php'));
}));
