<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.e0kEKNf' shared service.

return $this->privates['service_locator.e0kEKNf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventDispatcher' => function () {
    return ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService());
}));
