<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator._IK4IyU' shared service.

return $this->privates['service_locator._IK4IyU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('areaRepository' => function (): ?\App\Repository\AreaRepository {
    return ($this->privates['App\Repository\AreaRepository'] ?? $this->load(__DIR__.'/getAreaRepositoryService.php'));
}, 'encoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php'));
}));
