<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rIerrUe' shared service.

return $this->privates['service_locator.rIerrUe'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('posts' => function (): ?\App\Repository\PostRepository {
    return ($this->privates['App\Repository\PostRepository'] ?? $this->load(__DIR__.'/getPostRepositoryService.php'));
}));
