<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.h46VmrW' shared service.

return $this->privates['service_locator.h46VmrW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('areaRepo' => function (): ?\App\Repository\AreaRepository {
    return ($this->privates['App\Repository\AreaRepository'] ?? $this->load(__DIR__.'/getAreaRepositoryService.php'));
}));
