<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ELQewQI' shared service.

return $this->privates['service_locator.ELQewQI'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('encoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php'));
}, 'sistemRepository' => function (): ?\App\Repository\SistemRepository {
    return ($this->privates['App\Repository\SistemRepository'] ?? $this->load(__DIR__.'/getSistemRepositoryService.php'));
}));
