<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.t9fT.ZO' shared service.

return $this->privates['service_locator.t9fT.ZO'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('posts' => function (): ?\App\Repository\PostRepository {
    return ($this->privates['App\Repository\PostRepository'] ?? $this->load(__DIR__.'/getPostRepositoryService.php'));
}, 'sistemRepository' => function (): ?\App\Repository\SistemRepository {
    return ($this->privates['App\Repository\SistemRepository'] ?? $this->load(__DIR__.'/getSistemRepositoryService.php'));
}));
