<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxxCJ69\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxxCJ69/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNxxCJ69.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNxxCJ69\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNxxCJ69\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NxxCJ69',
    'container.build_id' => '0ea0ec1a',
    'container.build_time' => 1536750711,
));
